server:
  port: 8080

spring:
  application:
    name: demo
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=E-CommerceApiDb;encrypt=true;trustServerCertificate=true;
    username: ${DB_USERNAME:DuyDepTrai}
    password: ${DB_PASSWORD:goitaolabo1234}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jwt:
    secret: your-secret-key-must-be-long-enough-32-chars
    expiration: 86400000






